image: Visual Studio 2015   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

init:
    # секция инициализации, исполняется до клонирования проекта
    # скорее всего, строчка ниже необязательна (так должно быть по умолчанию),
    # вместе с тем, она присутствует в официальных примерах, так что пусть будет:
    - git config --global core.autocrlf input

clone_folder: c:\projects\my-prj # выбираем локальную директорию для клонирования
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    # будем гонять CI на amd64
    - x64
    
configuration:
    # ... и в дебажной, и в релизной конфигурациях ...
    - Debug
    - Release

environment:
    matrix:
        # ... на 2015
        - TOOLCHAIN: msvc14

install:
    # скрипт настройки среды и установки зависимостей:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
    - call ci\appveyor\script-windows.bat

build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%     # содержит нужный CMake-генератор
    - cmake --build . %CMAKE_BUILD_FLAGS%  # задаёт конфигурацию Debug/Release

artifacts:
    - path: <local-package-path>
      name: package_name

deploy:
    -   provider:      pages
        skip_cleanup:  true
        local_dir:     build/doc/html
        github_token:  $GITHUB_TOKEN

        on:
            branch:    master
            condition: $BUILD_DOC == ON

    -   provider:     releases
        file:         $DOXYREST_PACKAGE_FILE

        skip_cleanup: true
        overwrite:    true

        api_key:
            secure:   eFpWPF/1P1+DbHChlENnddunj4L8wdHHZvFUZoGXHwUgQ3xvo1CdKRtBo3Sv0HYftTlQjSrqCozx2tlunz9tNr6vKwLor7056MpqjmQsrujCVHhq1TsZd409ZkVR/3Dcl26yx6MMjVm43n6GAx3xLNna5hamq/G/7KggmAoJfWyT3bti4IIQrUw1w57Diyg1m778mXinAsKxy4IHFZR8LrxYKaNO4fATGBwNKJ3JUcTaE4Dap1IgDL8Mqu7c286ipzRFlJtTxRJPsMc3OkfSzgKQ2U7kfhU1pnRDEgd0D59MdUnU+4IZ5nQpbtNJejiEtozLz5YojKtDcvWEKujEQ/7bphEn/XwbCgH6dP6pximFvGphSCoKMjRkIqPN6oK1dQ7se63cCxNrc6r8/6C4GOIqrGQXf+7XCPLh2kdwJzOVG7fDvDWtd88szObROSWURBuMnxc3UP5WyS7zWkdgMMwIfuk96ZOwuRhdAWQ3K0/iHTK6PpCotGNqwKawJtgTj1v2mYXLoiecTbeKZ3ixfKlQX0XN5mx7/5kYKh5X0OGKgV7eTBSFF9Uc7gCjKld4vWrcTmi8V3OiZ5bzm+UGpWdIys3gHbE8sjVT3qvFuikyegfWniRDdvSWmcJrBm5/lIA9VjovapXmnQu3CAQ5MrzJp0QeDWArkmDjeeJMjZI=

        on:
            branch:    master
            tags:      true
            condition: $BUILD_PACKAGE == ON
